# Generated by Django 6.0.3 on 2026-03-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(blank=True, to='servicos.servico'),
        ),
    ]
